[Comic Settings]
Theme = homepage_is_latest_comic

[Pages]
archive = Archive - Happy Trails Quest #1
infinite_scroll = Infinite Scroll - Happy Trails Quest #1
latest =
cast = Cast
guide = What is Happy Trails Quest?
404 = Page Not Found
comics = Comics

[Links Bar]
Home = /
Comics = /comics/
Cast = /cast/
What is HTQ? = /happytrailsquestone/guide
Archive = /happytrailsquestone/archive/
Infinite Scroll = /happytrailsquestone/infinite_scroll/

[Archive]
# To use thumbnails in your archives, you must also set "Create thumbnails" to "True"
# in the [Image Reprocessing] section, or manually create your own
Use thumbnails = True
Date format = %m/%d/%Y

[Transcripts]
Enable transcripts = True
Default language = English