[Pages]
archive = Archive - Happy Trails Quest #1
infinite_scroll = Infinite Scroll - Happy Trails Quest #1
What is HTQ? = What is Happy Trails Quest?
404 = Page Not Found

[Links Bar]
Home = /
Happy Trails Quest #1 = /happytrailsquestone/comic/001
What is HTQ? = /guide
Archive = /happytrailsquestone/archive/
Infinite Scroll = /happytrailsquestone/infinite_scroll/
Patreon = ^https://www.patreon.com/cw/HappyTrailsComic

[Archive]
# To use thumbnails in your archives, you must also set "Create thumbnails" to "True"
# in the [Image Reprocessing] section, or manually create your own
Use thumbnails = True
Date format = %m/%d/%Y

[Transcripts]
Enable transcripts = True
Default language = English
