# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Syrup's Sloppy Spiel, Page 1
Post date = August 12, 2025
# You can delete any of the lines below if you don't want to use them.
Alt text = 
Storyline = Syrup's Sloppy Spiel
Characters = Maple, Syrup
Tags = Halloween