[Comic Settings]
Theme = homepage_is_latest_comic

[Pages]
archive = Archive - Night of the Lust Moon
infinite_scroll = Infinite Scroll - Night of the Lust Moon
latest =
cast = Cast
404 = Page Not Found
comics = Comics

[Links Bar]
Home = /
Comics = /comics/
Cast = /cast/
Archive = /nightofthelustmoon/archive/
Infinite Scroll = /nightofthelustmoon/infinite_scroll/

[Archive]
# To use thumbnails in your archives, you must also set "Create thumbnails" to "True"
# in the [Image Reprocessing] section, or manually create your own
Use thumbnails = True
Date format = %m/%d/%Y

[Transcripts]
Enable transcripts = True
Default language = English
