[Pages]
archive = Archive - Night of the Lust Moon
infinite_scroll = Infinite Scroll - Night of the Lust Moon
404 = Page Not Found

[Links Bar]
Home = /
Night of the Lust Moon = /nightofthelustmoon/comic/001
Archive = /nightofthelustmoon/archive/
Infinite Scroll = /nightofthelustmoon/infinite_scroll/
Patreon = ^https://www.patreon.com/cw/HappyTrailsComic

[Archive]
# To use thumbnails in your archives, you must also set "Create thumbnails" to "True"
# in the [Image Reprocessing] section, or manually create your own
Use thumbnails = True
Date format = %m/%d/%Y

[Transcripts]
Enable transcripts = True
Default language = English
