[Pages]
archive = Archive - Syrup's Sloppy Spiel
infinite_scroll = Infinite Scroll - Syrup's Sloppy Spiel
404 = Page Not Found

[Links Bar]
Home = /
Syrup's Sloppy Spiel = /sloppyspiel/comic/001
Archive = /sloppyspiel/archive/
Infinite Scroll = /sloppyspiel/infinite_scroll/
Patreon = ^https://www.patreon.com/cw/HappyTrailsComic

[Archive]
# To use thumbnails in your archives, you must also set "Create thumbnails" to "True"
# in the [Image Reprocessing] section, or manually create your own
Use thumbnails = True
Date format = %m/%d/%Y

[Transcripts]
Enable transcripts = True
Default language = English
