[Comic Settings]
Theme = homepage_is_latest_comic

[Pages]
archive = Archive - Syrup's Sloppy Spiel
infinite_scroll = Infinite Scroll - Syrup's Sloppy Spiel
cast = Cast
404 = Page Not Found
latest =
comics = Comics

[Links Bar]
Home = /
Comics = /comics/
Cast = /cast/
Archive = /sloppyspiel/archive/
Infinite Scroll = /sloppyspiel/infinite_scroll/

[Archive]
# To use thumbnails in your archives, you must also set "Create thumbnails" to "True"
# in the [Image Reprocessing] section, or manually create your own
Use thumbnails = True
Date format = %m/%d/%Y

[Transcripts]
Enable transcripts = True
Default language = English
