# Uncomment the line below to give your comic page a specific title, otherwise comic_git will use the name of the image file
Title = Happy Trails Quest 1 - Page 3
Post date = March 7, 2026
# You can delete any of the lines below if you don't want to use them.
Alt text = 
Storyline = Happy Trails Quest
Characters = Maple, Syrup
Tags = Happy Trails Quest